catalogue:
  image:
    repository: public.ecr.aws/h3m5h5w2/craftista/catalogue
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  service:
    type: ClusterIP
    port: 5000

frontend:
  image:
    repository: public.ecr.aws/h3m5h5w2/craftista/frontend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  service:
    type: LoadBalancer
    port: 80

  ingress:
    enabled: false

recommendation:
  image:
    repository: public.ecr.aws/h3m5h5w2/craftista/recommendation
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  service:
    type: ClusterIP
    port: 8080

voting:
  image:
    repository: public.ecr.aws/h3m5h5w2/craftista/voting
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  service:
    type: ClusterIP
    port: 8080
