name: Catalogue CI/CD

on:
  workflow_call: 
    
jobs:
  build-and-test:
    runs-on: minikube-wsl
    defaults:
      run:
        working-directory: ./catalogue
  
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ vars.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Test
        run: |
          pytest
