name: Catalogue CI

on:
  push:
    branches: 
      - "catalogue-ci"
  pull_request:
    branches:
      - "main"
    paths:
      - "catalogue/**"
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./catalogue
  
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ vars.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
