name: Package

on:
  workflow_call: 
    inputs:
      module:
        required: true
        type: string
      if:
        description: 'Whether to run this job'
        required: false
        default: false
        type: boolean

jobs:
  package:
    if: ${{ inputs.if }}
    name: ${{ inputs.module }}
    runs-on: minikube-wsl
    defaults:
      run:
        working-directory: ./${{ inputs.module }}
    
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./${{ inputs.module }}
        push: true
        tags:
          xledbd/craftista-${{ inputs.module }}:${{ github.event.pull_request.number }}
