name: Package

on:
  workflow_call: 
    inputs:
      module:
        required: true
        type: string

jobs:
  package:
    name: ${{ inputs.module }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./${{ inputs.module }}"
    
    steps:
    - uses: actions/checkout@v4
    - name: Login to ECR
      uses: docker/login-action@v3
      with:
        registry: public.ecr.aws
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        cache-from: type=gha
        cache-to: type=gha
        context: "./${{ inputs.module }}"
        push: true
        tags:
          "public.ecr.aws/${{ vars.AWS_ECR_ALIAS }}/craftista/${{ inputs.module }}:${{ github.event.pull_request.number }}"
