name: Pull Request uninstall

on:
  pull_request: 
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - 'catalogue/**'
      - 'recommendation/**'
      - 'voting/**'
    types: 
      - closed

jobs:
  uninstall-dev:
    runs-on: minikube-wsl

    steps:
    - name: Run helm uninstall
      run: >-
        helm uninstall dev 
        --wait -n ${{ github.event.pull_request.number }} 
    - name: Delete k8s namespace
      run:
        kubectl delete namespace ${{ github.event.pull_request.number }}

  delete-deployment:
    runs-on: minikube-wsl
    name: Delete deployment

    steps:
    - name: Delete Deployment Environment
      uses: strumwolf/delete-deployment-environment@v3.0.0
      with:
        environment: dev
        token: ${{ secrets.GITHUB_TOKEN }}
        onlyRemoveDeployments: true
