name: Reccomendation CI

on:
  push:
    branches: 
      - "main"
    paths:
      - "reccomendation/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "reccomendation/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./reccomendation

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ vars.GO_VERSION }}
          cache-dependency-path: reccomendation/go.sum
      - name: Build
        run: go build -v
      - name: Test
        run: go test
