name: Recommendation CI

on:
  push:
    branches: 
      - "main"
    paths:
      - "recommendation/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "recommendation/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./recommendation

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ vars.GO_VERSION }}
          cache-dependency-path: recommendation/go.sum
      - name: Build
        run: go build -v
      - name: Test
        run: go test

  package:
    needs: build-and-test
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./recommendation
    
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./recommendation
        push: true
        tags:
          xledbd/craftista-recommendation:latest
