name: Reusable workflows test

on:
  pull_request: 
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - 'catalogue/**'
      - 'recommendation/**'
      - 'voting/**'
    types: 
      - opened
      - closed
      - reopened
      - synchronize

jobs:
  changed-files:
    runs-on: minikube-wsl
    outputs:
      frontend: ${{ steps.changed-files.outputs.frontend_any_changed }}
      catalogue: ${{ steps.changed-files.outputs.catalogue_any_changed }}
      recommendation: ${{ steps.changed-files.outputs.recommendation_any_changed }}
      voting: ${{ steps.changed-files.outputs.voting_any_changed }}
    steps:
    - uses: actions/checkout@v4
  
    - name: Get changed files in all modules
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        files_yaml: |
          frontend:
            - frontend/**
          catalogue:
            - catalogue/**
          recommendation:
            - recommendation/**
          voting:
            - voting/**

  build-frontend:
    needs: changed-files
    name: Build Frontend
    uses: ./.github/workflows/frontend.yml
    if: needs.changed-files.outputs.frontend == 'true'

  build-catalogue:
    needs: changed-files
    name: Build Catalogue
    uses: ./.github/workflows/catalogue.yml
    if: needs.changed-files.outputs.catalogue == 'true'

  build-recommendation:
    needs: changed-files
    name: Build Recommendation
    uses: ./.github/workflows/recommendation.yml
    if: needs.changed-files.outputs.recommendation == 'true'

  build-voting:
    needs: changed-files
    name: Build Voting
    uses: ./.github/workflows/voting.yml
    if: needs.changed-files.outputs.voting == 'true'

  package:
    needs: [changed-files, build-catalogue, build-frontend, build-recommendation, build-voting]
    if: ${{ !failure() && !cancelled() }}
    strategy:
      matrix:
        module:
        - frontend
        - catalogue
        - recommendation
        - voting
        exclude:
        - module: ${{ needs.changed-files.outputs.frontend != 'true' && 'frontend'}}
        - module: ${{ needs.changed-files.outputs.catalogue != 'true' && 'catalogue'}}
        - module: ${{ needs.changed-files.outputs.recommendation != 'true' && 'recommendation'}}
        - module: ${{ needs.changed-files.outputs.voting != 'true' && 'voting'}}
    name: Package
    uses: ./.github/workflows/package.yml
    with:
      module: ${{ matrix.module }}
    secrets: inherit

  deploy-dev:
    needs: [changed-files, package]
    if: github.event_name == 'pull_request' && github.event.action != 'closed' && !failure() && !cancelled()
    runs-on: minikube-wsl
    
    steps:
    - run: echo ${{ needs.changed-files.outputs.changed_keys }}
