name: Github script test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: minikube-wsl

    steps:
    - name: Get PR number
      id: get-pr-number
      run: >-
        echo "number=$(
        curl -L 
        -H "Accept: application/vnd.github+json" 
        -H "X-GitHub-Api-Version: 2022-11-28" 
        https://api.github.com/repos/xledbd/craftista/commits/a6adf1ebc739cc292557b22e711e5f1c6b077ded/pulls |
        yq '.[0].number'
        )" >> "$GITHUB_OUTPUT"

    - name: Debug output
      run: echo "${{ steps.get-pr-number.outputs.number }}"
