name: Voting CI

on:
  push: 
    branches: 
      - "main"
    paths: 
      - "voting/**"
  pull_request:  
    branches: 
      - "main"
    paths: 
      - "voting/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./voting
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "23"
          cache: maven
          cache-dependency-path: voting/pom.xml
      - name: Build and test
        run: mvn -B package
