name: Voting CI

on:
  push: 
    branches: 
      - "main"
    paths: 
      - "voting/**"
  pull_request:  
    branches: 
      - "main"
    paths: 
      - "voting/**"

jobs:
  build-and-test:
    runs-on: minikube-wsl
    defaults:
      run:
        working-directory: ./voting
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "23"
          cache: maven
          cache-dependency-path: voting/pom.xml
      - name: Build and test
        run: mvn -B package
  
  package:
    needs: build-and-test
    if: github.event_name != 'pull_request'
    runs-on: minikube-wsl
    defaults:
      run:
        working-directory: ./voting
    
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./voting
        push: true
        tags:
          xledbd/craftista-voting:latest
